### ISSUE TITLE
Pointer type documentation

### ISSUE THREAD

**Issue by pierrre** [clipperhouse/gen#76]
There is nothing in the documentation about pointer type.
(or I haven't seen it)

The changelog contains a line:
https://github.com/clipperhouse/gen/blob/master/CHANGELOG.md
```
The * is a directive to generate methods which take a pointer type instead of a value type. Optional but recommended.
```

**Comment by clipperhouse** [comment]
Thanks, finally got around to this.

**Comment by pierrre** [comment]
Thank you! :+1:
