### ISSUE TITLE
Bug when _test.go files contains package_test as package name

### ISSUE THREAD

**Issue by SchumacherFM** [clipperhouse/gen#86]
Nice project! :+1: 

My package `utils` contains test files with the package name `utils_test` to test the public API.

File `stringSlice.go` contains e.g.:

```
// +gen slice:"Where,Count,GroupBy[int64]"
type Int64Slice []int64
```

Running then `gen` gives me the following error:

```
stringSlice_test.go:20:2: could not import github.com/project/csfw/utils (can't find import: github.com/project/csfw/utils)
```

Renaming `util_test` to `utils` and then running `gen` does work. But I don't want to do that.

Am I doing something wrong?

**Comment by clipperhouse** [comment]
It’s likely I haven’t tested with test packages having different names. Can you point to your code so I can repro?

**Comment by SchumacherFM** [comment]
That is the package https://github.com/corestoreio/csfw/tree/master/utils
You can run tests inside the package utils without setting up anything.
Running `gen` will of course fail.

**Comment by clipperhouse** [comment]
Sorry for the late response – am not getting a repro here. @SchumacherFM

**Comment by SchumacherFM** [comment]
```
$ go get github.com/corestoreio/csfw
$ cd $GOPATH/src/github.com/corestoreio/csfw/utils
$ gen
Int64Slice_test.go:20:2: could not import github.com/corestoreio/csfw/utils (can't find import: github.com/corestoreio/csfw/utils)
```

Can you now reproduce it?

**Comment by SchumacherFM** [comment]
Won't fix - it's an internal "Go bug"

**Comment by redbaron** [comment]
@SchumacherFM , I see same problem, could you please share what it was caused with and maybe possible workarounds you found?

**Comment by SchumacherFM** [comment]
I wrote my own internal code gen stuff ;-)
