### ISSUE TITLE
Specifying T from another package got illegal character '.'

### ISSUE THREAD

**Issue by c9s** [clipperhouse/gen#88]
I have the following code:

```go
package symtable
import "c6/ast"

// +gen symtable:"SymTable[ast.Function]"
type FunctionSymTable map[string]*ast.Function
```

When I run `gen`, I got this unexpected message:

```
symtable.go:15:32: illegal character '.' in type declaration
```

Is this by design? or is there a way to make it work? Thanks!

**Comment by clipperhouse** [comment]
@c9s Thanks, I will need to look into the implications of evaluating external packages…it might be non-trivial from a type-checking perspective.

**Comment by c9s** [comment]
Hi @clipperhouse I have sent a PR for this. and I think I will submit another PR for the external type support.
