### ISSUE TITLE
Broken under Go 1.6 (at least)

### ISSUE THREAD

**Issue by AmandaCameron** [clipperhouse/gen#98]
I've been trying to toy with using this under Go 1.6 however no matter what I do I get `some-file.go: ... could not import any/imported/package (Config.Importer not installed)` from any `gen` command I run in any non-trivial package. (Even under the `gen` package itself!)

This is rather sad, as I was hoping to toy with this for some personal projects. I've tried looking through the issues of this and typewriter, and havn't found any comparable bugs, so I filed this.

**Comment by hut8** [comment]
Do you get the same error with Go 1.5? Can you provide specific steps (platform, repo, etc)? I've used this under 1.6 with no issue.

**Comment by urandom** [comment]
I had the same (or similar problem) when testing gen. It turns out that it requires GOROOT to be set, which imho is wrong, since only GOPATH is a requirement. If that is really the case, it should ask the go tool what GOROOT is, since it always knows.

**Comment by AmandaCameron** [comment]
If I had to guess, this is caused by ysing the go/types package incorrectly, since the main result for googling the error is it's defintion in that package.

I've tried setting GOROOT as @urandom suggested, but that didn't help.

I'm using the go 1.6 packages on Gentoo, I'll give it a try with manually installing it sometime tomorrow if I have time.

**Comment by Kane-Sendgrid** [comment]
it seems under go 1.6 it can't find any imports other than stdlib

**Comment by clipperhouse** [comment]
How is this looking after pulling the latest? Did [this](https://github.com/clipperhouse/typewriter/commit/1cfecbcfb5a32a67d548c9b364e701b63c9d50b1) help?

**Comment by AmandaCameron** [comment]
Indeed it did, that PR which I submitted was what it took to make it start working under 1.6 from a new environment for me.
